### ISSUE TITLE
Perl execution error after PIN initialization

### ISSUE THREAD

**Issue by ryakel** [born-daniel/ecobee-perl#5]
First, thank you very much for generating these scripts. I am really looking forward to putting them to use. That said, I am getting an error after I have initialized the application with the pin. On the second execution of ecobee_mgr.pl that you describe in the Readme, I am getting the following error when trying to execute the script again.

```shell
# ./ecobee_mgr.pl 
=========ecobee_mgr.pl Start=========
Use of uninitialized value $p_thermostat_name in string eq at /usr/bin/ecobee/lib/Ecobee/Tools.pm line 32.
Use of uninitialized value $p_thermostat_name in string eq at /usr/bin/ecobee/lib/Ecobee/Tools.pm line 32.
Thermostat not defined at ./ecobee_mgr.pl line 349.
```
After enabling Debug, it appears to be related to the fact that I have two Ecobees in my account. The issue seems to originate from lib/Ecobee/Tools.pm in the sub Get_Thermostat_Id, specifically around line 28. 

```perl

  API::Get_Request($cmd, \%prop, \%results);

  my @revisionList = @{$results{revisionList}};
  my $revisionQty = @revisionList;

  my $use_default = ((!defined($p_thermostat_name)) and ($revisionQty == 1));
  my $revision;
  foreach $revision (@revisionList) {
    my @revisionParms = split(':', $revision);
    return ($revisionParms[0]) if (($use_default) or ($p_thermostat_name eq $revisionParms[1]));
  }

  # Thermostat not found!
  return (0);
}
```
When I change $revisionQty >=1, I can get the second thermostat to produce data and the error goes away. My perl is really weak, but I am hoping that this gives you enough information to guide me in the right direction.

Thank you again!

**Comment by born-daniel** [comment]
Hi ryakel,

Sorry for the late reply.
Would you happen to have more than 1 thermostat registered with ecobee? 
if so, you need to specify which one to use. If you only have one, this 
code was supposed to be able to handle this undefined value.

Let me know,
Daniel

**Comment by born-daniel** [comment]
Hi ryakel,

Sorry I'm not very active on here anymore. You need to specify your thermostat's ID as a parameter to function call Tools::Get_Thermostat_Id("xxxx");

If you only have 1 tstat registered (as I do), you don't need to specify anything but if you do have more than one, this is where you need to identify which one you want to access.

Hope this helps,
Daniel

**Comment by born-daniel** [comment]
Issue seems to not be a problem anymore. I will close it.
